In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("fact_water_samples.csv")
df.head()

,Sample_ID,Timestamp,Location_ID,Water_Temp_C,pH_Level,Turbidity_NTU,Dissolved_Oxygen_mgL,Microplastic_Count_per_m3,Dominant_Polymer,Dominant_Morphology,Average_Particle_Size_mm,Risk_Level
0,SMP-2026-0001,2026-01-01 00:00:00,LOC-107,9.2,7.38,33.32,10.62,552,PE,Fiber,0.06,High
1,SMP-2026-0002,2026-01-01 04:00:00,LOC-104,8.6,8.37,23.87,11.34,422,PS,Foam,0.21,High
2,SMP-2026-0003,2026-01-01 08:00:00,LOC-108,22.3,7.35,1.95,7.77,39,PET,Film,0.06,Low
3,SMP-2026-0004,2026-01-01 12:00:00,LOC-105,15.2,7.76,39.15,8.69,529,PS,Fiber,2.28,High
4,SMP-2026-0005,2026-01-01 16:00:00,LOC-107,10.5,7.41,3.38,11.15,87,PS,Foam,1.49,Low

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Sample_ID                  1000 non-null   object
 1   Timestamp                  1000 non-null   object
 2   Location_ID                1000 non-null   object
 3   Water_Temp_C               1000 non-null   float64
 4   pH_Level                   1000 non-null   float64
 5   Turbidity_NTU              1000 non-null   float64
 6   Dissolved_Oxygen_mgL       1000 non-null   float64
 7   Microplastic_Count_per_m3  1000 non-null   int64
 8   Dominant_Polymer           1000 non-null   object
 9   Dominant_Morphology        1000 non-null   object
 10  Average_Particle_Size_mm   1000 non-null   float64
 11  Risk_Level                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [5]:
df.describe()

,Water_Temp_C,pH_Level,Turbidity_NTU,Dissolved_Oxygen_mgL,Microplastic_Count_per_m3,Average_Particle_Size_mm
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,17.795700,7.397250,23.214520,8.654590,370.942000,1.720340
std,5.741221,0.497597,12.763028,1.789129,246.586718,0.995794
min,8.000000,5.780000,0.520000,4.760000,21.000000,0.050000
25%,12.875000,7.070000,12.385000,7.160000,182.000000,0.915000
50%,17.700000,7.410000,23.885000,8.670000,321.000000,1.675000
75%,22.800000,7.740000,34.362500,10.180000,524.500000,2.570000
max,28.000000,8.960000,44.990000,12.530000,1135.000000,3.500000

In [6]:
df.isnull().sum()

Sample_ID                    0
Timestamp                    0
Location_ID                  0
Water_Temp_C                 0
pH_Level                     0
Turbidity_NTU                0
Dissolved_Oxygen_mgL         0
Microplastic_Count_per_m3    0
Dominant_Polymer             0
Dominant_Morphology          0
Average_Particle_Size_mm     0
Risk_Level                   0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['Sample_ID'].duplicated().sum()

np.int64(0)

In [9]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')

In [10]:
df['Timestamp'].isnull().sum()

np.int64(0)

In [11]:
print(df['Dominant_Polymer'].unique())
print(df['Dominant_Morphology'].unique())
print(df['Risk_Level'].unique())

['PE' 'PS' 'PET' 'PVC' 'PP' 'PA']
['Fiber' 'Foam' 'Film' 'Microbead' 'Fragment']
['High' 'Low' 'Critical' 'Medium']

In [12]:
df['Risk_Level'] = df['Risk_Level'].str.strip().str.title()
df['Dominant_Polymer'] = df['Dominant_Polymer'].str.strip().str.upper()
df['Dominant_Morphology'] = df['Dominant_Morphology'].str.strip().str.title()

In [13]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:")
print(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())
print("Duplicate Sample IDs:", df['Sample_ID'].duplicated().sum())

Rows: 1000
Columns: 12
Missing values:
Sample_ID                    0
Timestamp                    0
Location_ID                  0
Water_Temp_C                 0
pH_Level                     0
Turbidity_NTU                0
Dissolved_Oxygen_mgL         0
Microplastic_Count_per_m3    0
Dominant_Polymer             0
Dominant_Morphology          0
Average_Particle_Size_mm     0
Risk_Level                   0
dtype: int64
Duplicate rows: 0
Duplicate Sample IDs: 0

In [14]:
df.to_csv('cleaned_fact_water_samples.csv', index=False)