In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("ml_predictions.csv")

In [2]:
df.head()

,Sample_ID,Actual_Microplastic_Count,Predicted_Microplastic_Count,Contamination_Risk_Score_Pct,Anomaly_Flag,Model_Confidence_Score
0,SMP-2026-0001,552,525,52.5,False,0.863
1,SMP-2026-0002,422,448,44.8,False,0.897
2,SMP-2026-0003,39,41,4.1,False,0.861
3,SMP-2026-0004,529,555,55.5,False,0.910
4,SMP-2026-0005,87,95,9.5,False,0.960

In [3]:
df.tail()

,Sample_ID,Actual_Microplastic_Count,Predicted_Microplastic_Count,Contamination_Risk_Score_Pct,Anomaly_Flag,Model_Confidence_Score
995,SMP-2026-0996,623,603,60.3,False,0.910
996,SMP-2026-0997,206,218,21.8,False,0.979
997,SMP-2026-0998,230,215,21.5,False,0.973
998,SMP-2026-0999,604,609,60.9,False,0.928
999,SMP-2026-1000,473,474,47.4,False,0.868

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Sample_ID                     1000 non-null   object
 1   Actual_Microplastic_Count     1000 non-null   int64
 2   Predicted_Microplastic_Count  1000 non-null   int64
 3   Contamination_Risk_Score_Pct  1000 non-null   float64
 4   Anomaly_Flag                  1000 non-null   bool
 5   Model_Confidence_Score        1000 non-null   float64
dtypes: bool(1), float64(2), int64(2), object(1)
memory usage: 40.2+ KB

In [6]:
df.shape

(1000, 6)

In [7]:
df.columns

Index(['Sample_ID', 'Actual_Microplastic_Count',
       'Predicted_Microplastic_Count', 'Contamination_Risk_Score_Pct',
       'Anomaly_Flag', 'Model_Confidence_Score'],
      dtype='object')

In [8]:
df.describe()

,Actual_Microplastic_Count,Predicted_Microplastic_Count,Contamination_Risk_Score_Pct,Model_Confidence_Score
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,370.942000,370.868000,36.971600,0.915566
std,246.586718,249.143716,24.592786,0.037875
min,21.000000,21.000000,2.100000,0.850000
25%,182.000000,183.750000,18.375000,0.883000
50%,321.000000,318.000000,31.800000,0.916000
75%,524.500000,528.000000,52.800000,0.948250
max,1135.000000,1179.000000,100.000000,0.980000

In [9]:
df.isnull().sum()

Sample_ID                       0
Actual_Microplastic_Count       0
Predicted_Microplastic_Count    0
Contamination_Risk_Score_Pct    0
Anomaly_Flag                    0
Model_Confidence_Score          0
dtype: int64

In [11]:
df.dtypes

Sample_ID                        object
Actual_Microplastic_Count         int64
Predicted_Microplastic_Count      int64
Contamination_Risk_Score_Pct    float64
Anomaly_Flag                       bool
Model_Confidence_Score          float64
dtype: object

In [12]:
df[df['Actual_Microplastic_Count'] < 0]
df[df['Predicted_Microplastic_Count'] < 0]

Empty DataFrame
Columns: [Sample_ID, Actual_Microplastic_Count, Predicted_Microplastic_Count, Contamination_Risk_Score_Pct, Anomaly_Flag, Model_Confidence_Score]
Index: []

In [13]:
df[
    (df['Contamination_Risk_Score_Pct'] < 0) |
    (df['Contamination_Risk_Score_Pct'] > 100)
]

Empty DataFrame
Columns: [Sample_ID, Actual_Microplastic_Count, Predicted_Microplastic_Count, Contamination_Risk_Score_Pct, Anomaly_Flag, Model_Confidence_Score]
Index: []

In [14]:
df[
    (df['Model_Confidence_Score'] < 0) |
    (df['Model_Confidence_Score'] > 1)
]

Empty DataFrame
Columns: [Sample_ID, Actual_Microplastic_Count, Predicted_Microplastic_Count, Contamination_Risk_Score_Pct, Anomaly_Flag, Model_Confidence_Score]
Index: []

In [15]:
df['Model_Confidence_Pct'] = df['Model_Confidence_Score'] * 100

In [16]:
df['Anomaly_Flag'].value_counts()

Anomaly_Flag
False    896
True     104
Name: count, dtype: int64

In [17]:
df['Prediction_Error'] = (
    df['Predicted_Microplastic_Count'] -
    df['Actual_Microplastic_Count']
)

In [20]:
df['Absolute_Error'] = abs(df['Prediction_Error'])

In [21]:
df['Error_Percentage'] = (
    df['Absolute_Error'] /
    df['Actual_Microplastic_Count'].replace(0, 1)
) * 100

In [22]:
df[df['Error_Percentage'] > 20]

Empty DataFrame
Columns: [Sample_ID, Actual_Microplastic_Count, Predicted_Microplastic_Count, Contamination_Risk_Score_Pct, Anomaly_Flag, Model_Confidence_Score, Model_Confidence_Pct, Prediction_Error, Absolute_Error, Error_Percentage]
Index: []

In [23]:
df.describe()

,Actual_Microplastic_Count,Predicted_Microplastic_Count,Contamination_Risk_Score_Pct,Model_Confidence_Score,Model_Confidence_Pct,Prediction_Error,Absolute_Error,Error_Percentage
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,370.942000,370.868000,36.971600,0.915566,91.556600,-0.074000,18.716000,5.102197
std,246.586718,249.143716,24.592786,0.037875,3.787511,25.766965,17.700357,2.907460
min,21.000000,21.000000,2.100000,0.850000,85.000000,-93.000000,0.000000,0.000000
25%,182.000000,183.750000,18.375000,0.883000,88.300000,-14.000000,5.000000,2.631579
50%,321.000000,318.000000,31.800000,0.916000,91.600000,0.000000,13.000000,5.218299
75%,524.500000,528.000000,52.800000,0.948250,94.825000,12.250000,27.000000,7.692308
max,1135.000000,1179.000000,100.000000,0.980000,98.000000,91.000000,93.000000,10.122699

In [24]:
df[['Predicted_Microplastic_Count',
    'Contamination_Risk_Score_Pct']].corr()

,Predicted_Microplastic_Count,Contamination_Risk_Score_Pct
Predicted_Microplastic_Count,1.000000,0.998955
Contamination_Risk_Score_Pct,0.998955,1.000000

In [25]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("Missing values:")
print(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

print("Duplicate Sample IDs:",
      df['Sample_ID'].duplicated().sum())

Rows: 1000
Columns: 10
Missing values:
Sample_ID                       0
Actual_Microplastic_Count       0
Predicted_Microplastic_Count    0
Contamination_Risk_Score_Pct    0
Anomaly_Flag                    0
Model_Confidence_Score          0
Model_Confidence_Pct            0
Prediction_Error                0
Absolute_Error                  0
Error_Percentage                0
dtype: int64
Duplicate rows: 0
Duplicate Sample IDs: 0

In [26]:
df.to_csv("cleaned_ml_predictions.csv", index=False)