In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("dim_locations.csv")
df.head()

,Location_ID,Location_Name,Water_Body_Type,Latitude,Longitude,City,State,Nearby_Industry_Type
0,LOC-101,Hudson River North,River,40.7128,-74.0060,New York,NY,Textile & Apparel
1,LOC-102,Lake Michigan Central,Lake,41.8781,-87.6298,Chicago,IL,Manufacturing
2,LOC-103,Bay Area Estuary,Estuary,37.7749,-122.4194,San Francisco,CA,Tech & Commercial
3,LOC-104,City WWTP Outlet,WWTP Effluent,40.7306,-73.9352,New York,NY,Municipal Sewage
4,LOC-105,Puget Sound Coastal,Coastal,47.6062,-122.3321,Seattle,WA,Maritime & Shipping

In [4]:
df.tail()

,Location_ID,Location_Name,Water_Body_Type,Latitude,Longitude,City,State,Nearby_Industry_Type
5,LOC-106,Mississippi Delta,River,29.9511,-90.0715,New Orleans,LA,Agriculture Runoff
6,LOC-107,Everglades Canal,Wetland,25.7617,-80.1918,Miami,FL,Agriculture Runoff
7,LOC-108,Delaware River Basin,River,39.9526,-75.1652,Philadelphia,PA,Chemical Processing
8,LOC-109,Lake Erie West,Lake,41.5055,-81.6944,Cleveland,OH,Heavy Industrial
9,LOC-110,Chesapeake Inflow,Estuary,38.9784,-76.4922,Annapolis,MD,Urban Runoff

In [5]:
df.columns

Index(['Location_ID', 'Location_Name', 'Water_Body_Type', 'Latitude',
       'Longitude', 'City', 'State', 'Nearby_Industry_Type'],
      dtype='object')

In [6]:
df.shape

(10, 8)

In [7]:
df.dtypes

Location_ID              object
Location_Name            object
Water_Body_Type          object
Latitude                float64
Longitude               float64
City                     object
State                    object
Nearby_Industry_Type     object
dtype: object

In [8]:
df.isnull().sum()

Location_ID             0
Location_Name           0
Water_Body_Type         0
Latitude                0
Longitude               0
City                    0
State                   0
Nearby_Industry_Type    0
dtype: int64

In [9]:
df.isna().sum()

Location_ID             0
Location_Name           0
Water_Body_Type         0
Latitude                0
Longitude               0
City                    0
State                   0
Nearby_Industry_Type    0
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df = df.drop_duplicates()

In [13]:
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [14]:
for col in text_columns:
    df[col] = df[col].str.title()

In [15]:
df['Latitude'] = pd.to_numeric(df['Latitude'], errors='coerce')
df['Longitude'] = pd.to_numeric(df['Longitude'], errors='coerce')

In [17]:
df.isnull().sum()

Location_ID             0
Location_Name           0
Water_Body_Type         0
Latitude                0
Longitude               0
City                    0
State                   0
Nearby_Industry_Type    0
dtype: int64

In [18]:
df.to_csv("dim_locations_cleaned.csv", index=False)