In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("dim_weather.csv")
df.head()

         Date Location_ID  Rainfall_mm  Wind_Speed_kmh  Surface_Runoff_Index
0  2026-01-01     LOC-101         0.00            33.4                  0.00
1  2026-01-02     LOC-101         0.00            29.1                  0.00
2  2026-01-03     LOC-101         0.00             6.8                  0.00
3  2026-01-04     LOC-101         6.57            24.9                  1.83
4  2026-01-05     LOC-101         7.40            30.8                  1.54

In [3]:
df.tail()

,Date,Location_ID,Rainfall_mm,Wind_Speed_kmh,Surface_Runoff_Index
1795,2026-06-25,LOC-110,0.00,34.6,0.00
1796,2026-06-26,LOC-110,0.74,7.0,0.53
1797,2026-06-27,LOC-110,1.91,20.1,0.54
1798,2026-06-28,LOC-110,0.36,27.7,0.19
1799,2026-06-29,LOC-110,0.00,30.9,0.00

In [5]:
df.shape

(1800, 5)

In [6]:
df.columns

Index(['Date', 'Location_ID', 'Rainfall_mm', 'Wind_Speed_kmh',
       'Surface_Runoff_Index'],
      dtype='object')

In [7]:
df.dtypes

Date                     object
Location_ID              object
Rainfall_mm             float64
Wind_Speed_kmh          float64
Surface_Runoff_Index    float64
dtype: object

In [8]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y', errors='coerce')

In [10]:
df.isnull().sum()

Date                    1800
Location_ID                0
Rainfall_mm                0
Wind_Speed_kmh             0
Surface_Runoff_Index       0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(173)

In [12]:
df = df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.describe()

      Date  Rainfall_mm  Wind_Speed_kmh  Surface_Runoff_Index
count    0  1627.000000     1627.000000           1627.000000
mean   NaT     2.146288       19.954456              1.039514
min    NaT     0.000000        5.000000              0.000000
25%    NaT     0.000000       12.300000              0.000000
50%    NaT     0.000000       20.200000              0.000000
75%    NaT     2.740000       27.100000              1.350000
max    NaT    30.680000       35.000000             23.180000
std    NaN     3.921628        8.637103              2.087508

In [17]:
df.to_csv("dim_weather_cleaned.csv", index=False)